infinitepixel-dev/InfinitePixel-Main

pnpm-lock.yaml

misc: updated lock

---

src/components/ContactForm.jsx

navbar now uses more width on mobile

ui: adjust contact form on smaller devices

---

src/components/utility/ScrollingIconsBar.jsx

scrolling icons now appear larger on mobile

ui: adjust scroll icons

---

src/components/Navbar.jsx

Updated logic for navbar menu items when open and clicked.

Updated nav with clickable logic based on menuItems when navbar is open.

---

src/components/Navbar.jsx

backdrop blur on navbar to more easily see content

ui: updated backblur on navbar

---

src/components/Navbar.jsx

bugfix: backdrop blur only applies on nav-menu being closed.

---

src/components/Footer.jsx

removed unused social links, also updated Facebook link. Will add more social pages down the road.

updated socials in footer

---

pnpm-lock.yaml
src/App.jsx

updated app for router v7. Will need to adjust further logic later on.

resolved merge conflict

---

src/components/pages/Portfolio.jsx

**New Content & Features:**
- Added new project entries to the portfolio.
- Implemented a call-to-action (CTA) to improve engagement.
- Integrated React Icons for each project card.
- Added tooltips to display technologies used per project.
**Styling & UX Enhancements:**
- Updated background and card styles to use a gradient.
- Refined animation logic for smoother interactions.
**Code Maintenance:**
- Removed unused components for cleaner codebase.

Enhance Portfolio Section with CTA, Animations, and Visual Updates

---

src/components/pages/Portfolio.jsx

correct animation glitch on certain devices

correct animation glitch on certain devices

---

src/components/ContactForm.jsx
src/components/Navbar.jsx
src/components/Review.jsx
src/components/pages/Portfolio.jsx

- **URL Placeholder**:
- Added a **TODO note** for linking to the updated **barbershop URL** once finalized.
- **Animated Waves**:
- Introduced **wave animations** to the Contact Form UI for a more engaging and polished visual experience.
- **Contact Us Logic Fix**:
- Corrected behavior in the **Contact Us** logic to ensure consistent routing and user interaction.

Contact Form Animation & Link Handling Fix

---

src/components/AboutUs.jsx
src/components/Review.jsx
src/components/WhatWeDo.jsx

- Fixed FontAwesome checkbox sizing issue: Ensured consistent height and width for all <FaCheckCircle /> icons across all devices.
- Removed unnecessary <hr> from the "What We Do" section for a cleaner mobile experience.
- Adjusted padding and card styles slightly to enhance readability and spacing on smaller screens.
- Added missing <b> tag in the "Why Use Infinite Pixel" section for improved emphasis and consistency.

Fix mobile layout inconsistencies and improve visibility in About/What We Do sections

---

src/components/ContactForm.jsx

Added additional padding to contact form

tweak: added padding to contact form

---

src/components/website/pages/ContactForm.jsx

updated padding for contact form on mobile

updated padding for contact form on mobile

---

src/components/website/Footer.jsx
src/components/website/cards/Map.jsx
src/components/website/pages/ContactForm.jsx
src/components/website/pages/WhatWeDo.jsx

This pull request addresses several accessibility improvements across the project:
- Added a title to the iframe: The iframe now includes a title="Google Map of Nashville, TN" for better context and support for screen readers.
- Fixed label association: The label element is correctly associated with the corresponding input field using htmlFor="email", improving accessibility for form elements.
- Refactored heading-like elements: Adjusted heading structure for better semantic organization and screen reader compatibility.
- Updated contact form heading: Changed h1 to h2 in the contact form for ADA compliance.
- Added aria-label to footer links: Ensured footer links have an aria-label for improved accessibility and screen reader context.
- SEO Improvements: Made various SEO adjustments, …

Enhance Accessibility: Add title to iframe & Improve Label Associations

---

src/components/website/Header.jsx
src/components/website/pages/ContactForm.jsx
src/components/website/pages/WhyCustomWebsite.jsx

added arial labels throughout app for ada compliance

aria label hotfix

---

src/App.jsx
src/components/website/pages/AboutUs.jsx
src/components/website/pages/ProjectStats.jsx

removed bullet point from list

added a stats component

---

package.json
pnpm-lock.yaml
src/App.jsx
src/components/website/Navbar.jsx
src/components/website/pages/Portfolio.jsx
src/components/website/utilities/AccessibleIcon.jsx
src/main.jsx

Updated the navbar and portfolio page for ADA/WCAG compliance. Implemented a dynamic accessible icon component.

refactor: updated ADA/WCAG compliance on navbar and portfolio page.

---

src/components/website/pages/AboutUs.jsx
src/components/website/pages/ContactForm.jsx

ui: updated contact page / waves padding. centered title text and updated alt tags on images.

ui: contact page layout changes

---

src/app/components/cards/ReviewCard.jsx
src/app/components/pages/AboutUs.jsx

This PR includes the following updates:
- Adjusted image width for better layout on desktop view.
- Resolved GSAP length error by moving ScrollTrigger.config() inside useEffect, ensuring it only runs client-side.
- Fixed missing key prop warning in ReviewCard by adding key={index} to .map() loop.

Fix desktop image width, resolve GSAP ScrollTrigger config error, and key prop warning

---

src/app/components/pages/ContactForm.jsx
src/app/components/pages/WhatWeDo.jsx
src/app/components/pages/WhyCustomWebsite.jsx

This PR includes the following updates:
- Resolved issue with links that were pointing to outdated articles
- Re-added border and font style adjustments (commit 0293402)
- Adjusted wave background for the contact form body section (e17a36e)
- Tweaked image width slightly to improve desktop display (f0f6aa4)

Fix article links, UI refinements, and desktop image adjustment

---

src/app/dashboard/login/LoginPage.jsx
src/app/register/RegisterPage.jsx
src/lib/firebaseClient.js

This PR introduces critical improvements to the Firebase authentication flow for registration and login:
- Ensures new user data is saved to Firestore correctly.
- Fixes getFirebaseInstance() usage to avoid invalid top-level await.
- Implements post-registration logout and redirect to login.
- Adds full login functionality using signInWithEmailAndPassword.
- Prepares routing for future use with dashboard subdomains.

Firebase Registration & Login Flow Improvements

---

src/app/dashboard/login/LoginPage.jsx
src/app/register/RegisterPage.jsx

This PR introduces front-end improvements to the authentication UI, focusing on user experience and visual clarity:
- Adds logic to toggle password visibility for better usability.
- Resolves layout conflicts where SVG icons were incorrectly layered above interactive elements.

UI Enhancements – Password Visibility & SVG Overlay Fixes

---

src/app/components/utils/InfinitePixelSpinner.jsx
src/app/dashboard/login/LoginPage.jsx
src/app/dashboard/register/RegisterPage.jsx

2e22804 – Added a reusable <InfinitePixelSpinner /> component and integrated it into the RegisterPage to display during registration submission.
- Adjusted spinner properties for improved visibility (centered layout and rainbow styling).
- Added a dev/debug toggle for manual spinner testing at line 66 of RegisterPage.jsx.
Changes Include:
- InfinitePixelSpinner.jsx: Created animated, rainbow-colored loading spinner with GSAP stagger.
- RegisterPage.jsx:
- Integrated the spinner for isSubmitting state.
- Added a showSpinner dev toggle and optional button for manual visibility control.
This improves UX during registration and provides a branded, visually engaging loading indicator that aligns with Infinite Pixel’s theme.

Spinner Integration & Debug Toggle

---

src/app/components/utils/InfinitePixelSpinner.jsx
src/app/dashboard/forgot-password/ForgotPasswordPage.jsx
src/app/dashboard/forgot-password/page.js
src/app/dashboard/login/LoginPage.jsx
src/app/dashboard/register/RegisterPage.jsx

- Integrated InfinitePixelSpinner into LoginPage for better sign-in feedback
- Added `isSubmitting` state to disable the login button and toggle loading spinner
- Login button now displays "Signing In..." during authentication
- Wrapped return block in a React fragment to conditionally render spinner
- Improved error handling for incorrect login credentials
- Applied consistent styling with background gradients and branding
- Created and routed a new ForgotPasswordPage component
- Matched Forgot Password page layout and design with login screen

 enhance login UX and add forgot password component

---

src/app/components/pages/BillingPage.jsx
src/app/dashboard/AdminDashboard.jsx
src/app/dashboard/billing/BillingPage.jsx
src/app/dashboard/billing/page.js
src/app/dashboard/login/LoginPage.jsx
src/app/dashboard/page.jsx
src/app/dashboard/settings/Settings.jsx
src/app/dashboard/settings/page.js

**feat(admin): display user first name on dashboard using localStorage**
- Retrieves userFirstName from localStorage and displays it dynamically in the welcome message.
- Ensures this logic executes on client-side mount using useEffect.
- Retains GSAP sidebar animation and layout functionality.
**feat(billing): implement full billing UI with subscription, invoices, and payment controls
Created BillingPage with the following sections:
- Subscription Details – status, next billing, update/cancel buttons
- Payment Method – masked card display, update button
- Invoice History – table with dates, amounts, status, and PDF download links
- Change Plan – button for upgrading/downgrading
- Cancel Subscription – confirmation UI
- Billing Contact Info – form for company, tax ID, and address
- Built …

Admin Dashboard Enhancements (Billing + Settings)

---

src/app/dashboard/AdminDashboard.jsx

ui: updated sidebar collapse logic and animations, adjusted logout icon/text logic

sidebar animation and logic update

---

src/app/dashboard/forgot-password/ForgotPasswordPage.jsx

This pull request finalizes the implementation of secure user login via Firebase Authentication. It introduces client-side logic for handling email/password-based login, improves user experience with dynamic feedback elements, and strengthens routing protections for authenticated areas of the application.
---
- Integrated `signInWithEmailAndPassword` using Firebase SDK
- Added error handling for invalid credentials and connection issues
- Implemented loading state via custom spinner for visual feedback
- Password visibility toggle for better usability
- Error messages displayed inline with form
- Automatic redirect to `/dashboard` upon successful login
- Client-side route guard logic to prevent unauthorized access to `/dashboard`
- Added `firebase logout` functionality for clean session …

version release to prod
